apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-backend
  namespace: board
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board-backend
  template:
    metadata:
      labels:
        app: board-backend
    spec:
      containers:
        - name: backend
          image: donkkaspapi/board-backend:arm64
          imagePullPolicy: Always  
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: board-backend
  namespace: board
spec:
  selector:
    app: board-backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30081
  type: NodePort
