apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-frontend
  namespace: board
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board-frontend
  template:
    metadata:
      labels:
        app: board-frontend
    spec:
      containers:
        - name: frontend
          image: donkkaspapi/board-frontend:arm64
          imagePullPolicy: Always  
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: board-frontend
  namespace: board
spec:
  selector:
    app: board-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
