apiVersion: v1
kind: Service
metadata:
  name: board-mysql
  namespace: board
spec:
  selector:
    app: board-mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-mysql
  namespace: board
spec:
  selector:
    matchLabels:
      app: board-mysql
  template:
    metadata:
      labels:
        app: board-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: board
          ports:
            - containerPort: 3306
          args:
            - "--default-authentication-plugin=mysql_native_password"
